config/routes.rb
Rails.application.routes.draw do
  resources :shopping_lists

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :shopping_list
end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
  has_many :products, dependent: :destroy
  accepts_nested_attributes_for :products, reject_if: lambda { |a| a[:name].blank? }, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :set_shopping_list, only: [:show, :edit, :update, :destroy]

  def index
    @shopping_lists = ShoppingList.all
  end

  def show
  end

  def new
    @shopping_list = ShoppingList.new
  end

  def edit
  end

  def create
    @shopping_list = ShoppingList.new(shopping_list_params)

    respond_to do |format|
      if @shopping_list.save
        format.html {redirect_to shopping_list_url(@shopping_list),
                                 notice: 'Shopping List was successfully created.'}
        format.json {render :show, status: :created, location: @shopping_list}
      else
        format.html {render :new}
        format.json {render json: @shopping_list.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @shopping_list.update(shopping_list_params)
        format.html {redirect_to @shopping_list, notice: 'Shopping List was successfully updated.'}
        format.json {render :show, status: :ok, location: @shopping_list}
      else
        format.html {render :edit}
        format.json {render json: @shopping_list.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @shopping_list.destroy
    respond_to do |format|
      format.html { redirect_to shopping_lists_url, notice: 'Shopping List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_shopping_list
    @shopping_list = ShoppingList.find(params[:id])
  end

  def shopping_list_params
    params.require(:shopping_list).permit(:title, :was_bought, products_attributes: [:name, :quantity])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to(name, "javascript:void(0)", onclick: "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, child_index: "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to(name, "javascript:void(0)", onclick: h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
  end

end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTestingPos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<main class="container" role="main">
  <%= yield %>
</main>

</body>
</html>

app/views/shopping_lists/_form.html.erb
<%= form_for([@shopping_list]) do |f| %>
  <% if @shopping_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @shopping_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title , class: 'form-control',:required => true%>
  </div>
   <div class="form-group">
    <%= f.label :was_bought %><br>
    <%= f.check_box :was_bought, {}, true, false %>
  </div>


  <%= f.fields_for :products do |builder| %>
    <%= render "product_fields", f: builder %>
  <% end %>

    <div class="add-products">
      <i class="fas fa-cart-plus"></i>
      <%= link_to_add_fields "Add Product", f, :products %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopping_lists/_product_fields.html.erb
<div class="form-row fields">
  <div class="form-group col-md-6">
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, class: 'form-control'%>
  </div>
  <div class="form-group col-md-4">
    <%= f.label :quantity, "Quantity" %>
    <%= f.number_field :quantity,class: 'form-control' %>
  </div>
  <div class="form-group col-md-2">
    <%= f.hidden_field :_destroy %>
    <%= link_to_remove_fields icon('fas', 'trash-alt'), f %>
  </div>
</div>

app/views/shopping_lists/edit.html.erb
<h3>Edit Shopping List</h3>

<%= render 'form' %>

<%= link_to 'Show', @shopping_lists %> |
<%= link_to 'Back', shopping_lists_path %>

app/views/shopping_lists/index.html.erb
<div class="alert alert-warning alert-dismissible fade show " role="alert">
  <%= notice %>
</div>

<h2>Shopping Lists</h2>
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Title</th>
    <th>Was bought</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @shopping_lists.each do |shopping_list| %>
    <tr>
      <td><%= shopping_list.title %></td>
      <td>
        <% if shopping_list.was_bought %>
          <i class="fas fa-cart-arrow-down"></i>
        <% end %>
        <i class="times-circle"></i>
      </td>
      <td><%= link_to icon('fas', 'eye'), shopping_list %></td>
      <td><%= link_to icon('fas', 'edit'), edit_shopping_list_path(shopping_list) %></td>
      <td><%= link_to icon('fas', 'trash-alt'), shopping_list, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Shopping List', new_shopping_list_path, :class => "add_shopping_list" %>

app/views/shopping_lists/new.html.erb
<h3>New Shopping List</h3>

<%= render 'form' %>

<%= link_to icon('fas', 'arrow-left'), shopping_lists_path %>

app/views/shopping_lists/show.html.erb
<div class="alert alert-warning alert-dismissible fade show " role="alert">
  <%= notice %>
</div>


<p>
  <strong>Title:</strong>
  <%= @shopping_list.title %>
</p>

<p>
  <strong>was bought:</strong>
  <% if @shopping_list.was_bought %>
    <i class="fas fa-cart-arrow-down"></i>
  <% end %>
</p>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Quantity</th>
  </tr>
  <strong>Products:</strong>

  <% @shopping_list.products.each do |product| %>
    <tr>
      <th><%= product.name %></th>
      <th><%= product.quantity %></th>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', shopping_lists_path %>